<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Internship Logbook PDF</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #222; }
        .header { text-align: center; margin-bottom: 24px; }
        .header h2 { color: #000000; margin-bottom: 0; }
        .info-table { width: 100%; margin-bottom: 24px; }
        .info-table td { padding: 4px 8px; }
        .cover-title { font-size: 2rem; color: #000000; margin-bottom: 1.5rem; }
        .section-title { font-size: 1.2rem; margin: 2rem 0 1rem 0; color: #000000; }
        .log-table { width: 100%; border-collapse: collapse; page-break-inside: auto; }
        .log-table th, .log-table td {
            border: 1px solid #0F172A;
            padding: 8px;
            font-size: 0.98rem;
        }
        .log-table th {
            background: #0F172A;
            color: #fff;
        }
        .log-table tr:nth-child(even) { background: #f3f4f6; }
        .footer { margin-top: 32px; text-align: center; font-size: 0.95rem; color: #888; }
        .page-break { page-break-after: always; }
    </style>
</head>
<body>
    {{-- COVER PAGE --}}
    <div class="header">
        <div class="cover-title">MyInternLog</div>
        <div>Internship Logbook</div>
    </div>
    <table class="info-table">
        <tr>
            <td><strong>Name:</strong></td>
            <td>{{ $student->user->name }}</td>
        </tr>
        <tr>
            <td><strong>Student ID:</strong></td>
            <td>{{ $student->student_id }}</td>
        </tr>
        <tr>
            <td><strong>Email:</strong></td>
            <td>{{ $student->user->email }}</td>
        </tr>
        <tr>
            <td><strong>Program:</strong></td>
            <td>{{ $student->program }}</td>
        </tr>
        <tr>
            <td><strong>Semester:</strong></td>
            <td>{{ $student->semester }}</td>
        </tr>
        <tr>
            <td><strong>Phone:</strong></td>
            <td>{{ $student->phone }}</td>
        </tr>
        <tr>
            <td><strong>University Supervisor:</strong></td>
            <td>{{ $internship->universitySupervisor->user->name ?? '-' }}</td>
        </tr>
        <tr>
            <td><strong>Industry Supervisor:</strong></td>
            <td>{{ $internship->industrySupervisor->user->name ?? '-' }}</td>
        </tr>
        <tr>
            <td><strong>Company:</strong></td>
            <td>{{ $internship->company_name }}</td>
        </tr>
        <tr>
            <td><strong>Company Address:</strong></td>
            <td>{{ $internship->company_address }}</td>
        </tr>
        <tr>
            <td><strong>Internship Period:</strong></td>
            <td>{{ \Carbon\Carbon::parse($internship->start_date)->format('d M Y') }} - {{ \Carbon\Carbon::parse($internship->end_date)->format('d M Y') }}</td>
        </tr>
    </table>
    <div class="footer">
        Generated by MyInternLog &mdash; {{ now()->format('d M Y') }}
    </div>
    <div class="page-break"></div>

    {{-- REPORTS TABLE --}}
    <div class="section-title">Daily Reports</div>
    <table class="log-table">
        <thead>
            <tr>
                <th style="width: 13%;">Date</th>
                <th>Log</th>
                <th style="width: 13%;">Status</th>
                <th style="width: 22%;">University Supervisor Feedback</th>
                <th style="width: 22%;">Industry Supervisor Feedback</th>
            </tr>
        </thead>
        <tbody>
            @forelse($reports as $report)
                <tr>
                    <td>{{ \Carbon\Carbon::parse($report->report_date)->format('d M Y') }}</td>
                    <td>{{ $report->task }}</td>
                    <td>
                        @if($report->status == 'reviewed')
                            Reviewed
                        @else
                            Pending
                        @endif
                    </td>
                    <td>
                        {{ $report->uni_feedback ?? '-' }}
                    </td>
                    <td>
                        {{ $report->industry_feedback ?? '-' }}
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" style="text-align:center;">No reports found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>